### ISSUE TITLE
Rename `NeuraNet` library

### ISSUE THREAD

**Issue by JamorMoussa** [JamorMoussa/NeuraNet#7]
I suggest renaming the library from `NeuraNet` to `nanotorch` because the library is inspired by the PyTorch framework, and `NeuraNet` doesn't give any information that the library uses the PyTorch syntax. The `nano` keyword is chosen because the library will contain only a few features, similar to PyTorch.

The import statements would then look like:

```python
import nanotorch as nnt
import nanotorch.nn as nn
import nanotorch.optim as optim
```

**Comment by anas1IA** [comment]
I'm on board with `nanotorch`! It's concise, clear, and captures the essence of our library's connection to PyTorch while hinting at its streamlined features.

**Comment by JamorMoussa** [comment]
I'll make a pull request for this. But, before I've to test of there are any bugs after renaming the library.

**Comment by JamorMoussa** [comment]
@anas1IA
